### ISSUE TITLE
Sample problem

### ISSUE THREAD

**Issue by Simin-Du** [thu-ml/DiffusionBridge#2]
Thanks for the great work! One question is that when I run the sampling task, I meet some problems. Below is the detail:

created 0 samples
[rank2]: Traceback (most recent call last):
[rank2]:   File ".../DiffusionBridge-main/sample.py", line 204, in <module>
[rank2]:     main()
[rank2]:   File ".../DiffusionBridge-main/sample.py", line 157, in main
[rank2]:     arr = np.concatenate(all_images, axis=0)
[rank2]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: ValueError: need at least one array to concatenate

Can you help me to solve this problem. Thanks a lot.

**Comment by zhengkw18** [comment]
It seems that no images were created during the sampling process. 

The sampling script requires accessing the dataset to read the conditions. Did you process the dataset properly? Could you check whether `len(dataloader.dataset)` >0?
